#!/bin/bash
arm-none-eabi-as -o ts.o ts.s && \
arm-none-eabi-gcc -c t.c -o t.o -ggdb && \
arm-none-eabi-ld -T t.ld -o t.elf ts.o t.o && \
arm-none-eabi-nm t.elf && \
arm-none-eabi-objcopy -O binary t.elf t.bin
